namespace MultiplayerMod.Core.Objects;

/// <summary>
/// Type of <see cref="MultiplayerId"/>
/// </summary>
public enum MultiplayerIdType : byte
{
    /// <summary>
    /// Prefab, Chores or game Id
    /// </summary>
    Internal = 0,
    /// <summary>
    /// Generated by creation of the object
    /// </summary>
    Generated = 1
}
